if(NOT DEFINED OCS_EXTENSION_SOURCE OR NOT DEFINED OCS_EXTENSION_STAGE
   OR NOT DEFINED OCS_SOLVER_LIBRARY)
    message(FATAL_ERROR "Extension source, stage and solver library are required")
endif()

file(REMOVE_RECURSE "${OCS_EXTENSION_STAGE}")
file(MAKE_DIRECTORY "${OCS_EXTENSION_STAGE}/bin")
file(COPY "${OCS_EXTENSION_SOURCE}/"
     DESTINATION "${OCS_EXTENSION_STAGE}"
     PATTERN "__pycache__" EXCLUDE)
file(COPY "${OCS_SOLVER_LIBRARY}"
     DESTINATION "${OCS_EXTENSION_STAGE}/bin")
file(WRITE "${OCS_EXTENSION_STAGE}/.stage-complete" "staged\n")
